---
title: Farey Linked List
date: '2024-04-18'
slug: farey-linked-list

---

In my [last post](/blog/2024/04/10/farey-numbers-and-linked-lists) I talked about using Farey numbers as coordinates for linked list elements. Let's actually do it.

<!--more-->

<script src=" https://cdn.jsdelivr.net/npm/cytoscape@3.28.1/dist/cytoscape.min.js "></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/rxjs/7.8.1/rxjs.umd.min.js" integrity="sha512-D9LDs8YUUVa4V9Gl4Zb+xqRAc7RCzooR3+zzebgK2RMu/KU+dh90pbjEEMzPiSyRSGbSp9j1pZnrO4joGa5WEg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

```{css, echo=FALSE}
p > code {
    padding: 0 5px;
    margin: 0 2px;
    line-height: 2em;
}

body {
    line-height: 3em !important;
}

.katex {
    font-size: 1.1em !important;
    /*line-height: 1.7em !important;*/
    padding: 0 .15em;
    white-space: nowrap;
}

.cy {
    height: 8em;
    display: block;
}
```

```{js, echo=FALSE, attr.source='type="module"'}
let newId = function(left, right) {
    return {
        numerator: left.numerator + right.numerator,
        denominator: left.denominator + right.denominator
    }
}
let id = (element) => `${element.numerator}\n${element.denominator}`;

let graphit = function(element, destination, label='data(id)', fitpadding=30) {
    let cy = cytoscape({
        container: document.getElementById(destination), // container to render in
        elements: [ ],
        style: [ // the stylesheet for the graph
            {
                selector: 'node',
                style: {
                    'background-color': '#666',
                    'label': label,
                    'text-valign': 'bottom',
                    'text-margin-y': '1em',
                    'text-wrap': 'wrap',
                    'font-family': 'Merriweather, serif',
                    'width': "2em",
                    'height': "2em",
                    'font-size': '1.5em'
                }
            },
            {
                selector: 'edge',
                style: {
                    'width': ".5em",
                    'line-color': '#ccc',
                    'target-arrow-color': '#ccc',
                    'target-arrow-shape': 'triangle',
                    'curve-style': 'bezier'
                }
            }
        ],
        //panningEnabled: false,
        //userPanningEnabled: false,
        boxSelectionEnabled: false,
        autoungrabify: true,
        autounselectify: true
    });

    let focus;

    let doLayout = function(animate = false, fit = false) {
        //cy.clearQueue();
        cy.nodes().sort(function(n1, n2) {
            var l = n1.data('sort').numerator * n2.data('sort').denominator;
            var r = n2.data('sort').numerator * n1.data('sort').denominator;
            return (l - r) < 0n ? -1 : 1;
        }).layout({ 
            name: "grid", 
            rows: 1,
            avoidOverlapPadding: 200, 
            fit: fit, 
            animate: animate, 
            animationDuration: 200,
            center: { eles: [ focus ] } 
        }).run();
        cy.animate({ fit: { eles: focus, padding: fitpadding, duration: 300 } }) 
    }

    cy.on('tap', 'edge', function(evt, pos) {
        cy.remove(evt.target);

        var lnode = evt.target._private.data.leftnode
        var newel = insert(lnode);

        var newnode = cy.add({ 
            group: 'nodes', 
            data: { id: id(newel), sort: newel }, 
            position: pos ?? evt.position,
        });
        
        if (focus && focus.length == 1) {
            focus.animate({
                style: { 'background-color': '#5d686f' },
                duration: 50
            });
        }

        focus = newnode;
        newnode.animate(({
            style: { 'background-color': '#007FFF'},
            duration: 50
        }));

        cy.add({ 
            group: 'edges', 
            data: { 
                id: id(newId(lnode, newel)),
                source: id(lnode),
                target: id(newel),
                leftnode: lnode
            }});
        cy.add({ 
            group: 'edges', 
            data: { 
                id: id(newId(newel, newel.next)),
                source: id(newel),
                target: id(newel.next),
                leftnode: newel
            }});

        doLayout(true, false);
    })

    let last = undefined;
    let current = element;
    do {
        cy.add({ group: 'nodes', data: { id: id(current), sort: current }});

        if (last) {
            cy.add({
                group: 'edges', 
                data: { 
                    id: id(newId(last, current)), 
                    source: id(last), 
                    target: id(current),
                    leftnode: last
                }
            })
        }
        last = current;
        current = current.next;
    } while(current)

    focus = cy.elements();
    doLayout(false, true);
    rxjs.fromEvent(window, "resize").pipe(rxjs.debounceTime(200)).subscribe(doLayout);
    return cy;
}

let makeList = () => ({
    numerator: 0n,
    denominator: 1n,
    next: {
        numerator: 1n,
        denominator: 1n,
        next: undefined
    }
});

let insert = function(element) {
    // my kingdom for a type system
    if (!element || !element.next) {
        throw ":(";
    }

    // make the new element
    let newEl = {
        // it needs a Farey number
        // to make a new Farey number from two existing Farey numbers, 
        // you sum their numerators and denominators.
        numerator: element.numerator + element.next.numerator,
        denominator: element.denominator + element.next.denominator,

        // it points to what element currently points to.
        next: element.next
    };
    
    // insert the new element into the list by making element point to it.
    element.next = newEl;

    // return the new element
    return newEl;
}

let list = makeList();
```

In my [last post](/blog/2024/04/10/farey-numbers-and-linked-lists) I talked about using Farey numbers as coordinates for linked list elements. Here's what that looks like. Click a link to insert a new element into the list.

<div id="the-list" class="cy"></div>

```{js, echo=FALSE}
lecy = graphit(list, "the-list");
```

### Rationalizing the Irrational

We can use the Farey Linked List to find rational approximations of irrational numbers between zero and one. If we want to approximate a number greater than one, first we approximate the reciprocal of that number, then we take the reciprocal of that approximation. Let's do $\displaystyle\pi.$ $\displaystyle\pi$ is greater than one, so first we take its reciprocal which is ~$0.318$. The empty Farey Linked List has one edge that spans $\displaystyle0-1.$ $0.318$ is in that range, so we'll insert a node there. Now we have two edges. The first edge spans $0-\frac{1}{2}$, and the second edge spans $\frac{1}{2}-1.$ $0.318$ is in the first range, so we insert there. We can continue inserting until our approximation is good enough. Not every insertion we do will give us a better approximation immediately, but it will take us in the correct direction. The process looks like this (click the approximate button below).

<div id="pi" class="cy"></div>
<div class="center">$\displaystyle\pi =$<span id="pi-approximation">0</span><br /><button class="approx-pi btn btn--default">Approximate $\displaystyle\pi$</button></div>

```{js, echo=FALSE}
let makeApproximationHandler = function(toApproximaten, toApproximate, left, right, graph, button, output) {
    let bestApprox = 100;
    let bestError = 100;
    let count = 1000000;
    let handler = (event) => {
        button.removeEventListener("click", handler);
        approximationTimeout = setInterval(function() {
            newEl = insert(left);
            approx = 10000000000000000/Number(newEl.numerator*10000000000000000n / newEl.denominator);

            if (newEl.denominator > Number(toApproximaten * newEl.numerator)/10000000000000000) 
            {
                left = newEl;
            } 
            else if (newEl.denominator < Number(toApproximaten * newEl.numerator)/10000000000000000) 
            {
                right = newEl;
            }
            else 
            {
                clearTimeout(approximationTimeout);
            }

            le_element = graph.getElementById(id(newEl));
            le_element.emit('tap', le_element.midpoint());
            if (count-- == 0) {
                clearTimeout(approximationTimeout);
            }
            
            var error = Math.abs(toApproximate - approx);
            if (error < bestError) {
                bestError = error;
                bestApprox = approx;
                output.innerText = bestApprox;
            }
        }, 600);
    }
    button.addEventListener("click", handler);
}

let piList = makeList();

pigraph = graphit(makeList(), "pi");
let pileft = piList;
let piright = piList.next;

let pin = BigInt(Math.PI * 10000000000000000); 

makeApproximationHandler(pin, Math.PI, pileft, piright, pigraph, document.querySelector("button.approx-pi"), document.getElementById("pi-approximation"))
```

That might take awhile, let's do something else in the meantime. Here's $\displaystyle\phi.$

<div id="phi" class="cy"></div>
<div class="center">$\displaystyle\phi =$<span id="phi-approximation">0</span><br /><button class="approx-phi btn btn--default">Approximate $\displaystyle\phi$</button></div>

```{js, echo=FALSE}
let phiList = makeList();
let phigraph = graphit(makeList(), "phi");
let phileft = phiList;
let phiright = phiList.next;

let phi = (1 + Math.sqrt(5)) / 2;
let phin = BigInt(phi * 10000000000000000);

makeApproximationHandler(phin, phi, phileft, phiright, phigraph, document.querySelector("button.approx-phi"), document.getElementById("phi-approximation"));
```

Watch both closely. $\displaystyle\pi$ takes long runs in the same direction, while $\displaystyle\phi$ alternates directions every step. Alternating the direction the way $\displaystyle\phi$ does turns out to be the fastest way to make the numerator and denominator of the Farey Numbers grow. This is one manifestation of $\displaystyle\phi's$ reputation as "The Most Irrational Number".

