---
title: Farey Linked List
date: '2024-04-11'
slug: farey-linked-list

---

In my [last post](/blog/2024/04/10/farey-numbers-and-linked-lists) I talked about using Farey numbers as coordinates for linked list elements. Let's actually do it.

<!--more-->
 
<script src=" https://cdn.jsdelivr.net/npm/cytoscape@3.28.1/dist/cytoscape.min.js "></script>

```{css, echo=FALSE}
p > code {
    padding: 0 5px;
    margin: 0 2px;
    line-height: 2em;
}

body {
    line-height: 3em !important;
}

.katex {
    font-size: 1.1em !important;
    /*line-height: 1.7em !important;*/
    padding: 0 .15em;
    white-space: nowrap;
}

.cy {
    height: 150px;
    display: block;
}
```

```{js, echo=FALSE}
var cy = null;
let graphit = function(element, destination, label="data(id)") {
    cy = cytoscape({
        container: document.getElementById(destination), // container to render in
        elements: [ ],
        style: [ // the stylesheet for the graph
            {
                selector: 'node',
                style: {
                    'background-color': '#666',
                    'label': label,
                    'text-valign': 'bottom',
                    'text-margin-y': '1em',
                    'font-family': 'Merriweather, serif',
                    'font-size': '1.1em'
                }
            },
            {
                selector: 'edge',
                style: {
                    'width': 7,
                    'line-color': '#ccc',
                    'target-arrow-color': '#ccc',
                    'target-arrow-shape': 'triangle',
                    'curve-style': 'bezier'
                }
            }
        ],
        panningEnabled: false,
        boxSelectionEnabled: false,
        autoungrabify: true,
        autounselectify: true
    });

    let id = (element) => `${element.numerator}/${element.denominator}`;

    let last = undefined;
    let current = element;
    do {
        cy.add({ group: 'nodes', data: { id: id(current) }});

        if (last) {
            cy.add({
                group: 'edges', 
                data: { id: `${id(last)} -> ${id(current)}`, source: id(last), target: id(current) }})
        }
        last = current;
        current = current.next;
    } while(current)
    
    cy.layout({ name: "grid", rows: 1 }).run();
    /*cy.on('tap', 'edge', function(evt) {
        var node = evt.target;
        console.log(node);
        cy.remove(node);
        cy.add({ group: "nodes", data: { id: node.source }})
        //cy.layout({ name: "grid", rows: 1, animate: true });

        //graphit(element, destination, label);
    });*/
}
```

In my [last post](/blog/2024/04/10/farey-numbers-and-linked-lists) I talked about using Farey numbers as coordinates for linked list elements. Let's actually do it.

## Start with a linked list

A linked list is a sequence of elements, each one linked to the next. In javascript we might set up an empty linked list like this...

```{js}
// make one node
let begin = {
    next: undefined
}

// make another node
let end = {
    next: undefined
}

// "link!" – navi
begin.next = end;
```

And visualize it like this...

<div id="begin-end" class="cy"></div>

```{js, echo=FALSE}
begin.numerator = 0;
begin.denominator = 1;
begin.next.numerator = 1;
begin.next.denominator = 1;

graphit(begin, "begin-end", "")
```

We can terse up the code and give it a name.

```{js}
let makeList = () => ({
    next: {
        next: undefined
    }
});
```

## Add a pinch of Farey dust

Now we'll add the Farey numbers. `begin` is always $\displaystyle\frac{0}{1}$, and `end` is always $\displaystyle\frac{1}{1}$

```{js}
makeList = () => ({
    numerator: 0,
    denominator: 1,
    next: {
        numerator: 1,
        denominator: 1,
        next: undefined
    }
});

begin = makeList();
```

<div id="with-farey-numbers" class="cy"></div>

```{js, echo=FALSE}
graphit(begin, "with-farey-numbers", "data(id)");
```

We'd like to insert into the list. This function takes an element of the list and inserts a new element after it.

```{js}
let insert = function(element) {
    //my kingdom for a type system
    if (!element || !element.next) {
        throw ":(";
    }

    ///make the new element
    let newEl = {
        // it needs a Farey number
        // to make a new Farey number from two existing Farey numbers, 
        // you sum their numerators and denominators.
        numerator: element.numerator + element.next.numerator,
        denominator: element.denominator + element.next.denominator,

        // it points to what element currently points to.
        next: element.next
    };
    
    //insert the new element into the list by making element point to it.
    element.next = newEl;

    // return the new element
    return newEl;
}
```

If we insert an element after begin...

```{js}
let half = insert(begin);
```

We get

<div id="with-half" class="cy"></div>

```{js, echo=FALSE}
graphit(begin, "with-half");
```

We can do it again...

```{js}
let third = insert(begin);
let twothirds = insert(half);
```

<div id="with-third" class="cy"></div>

```{js, echo=FALSE}
graphit(begin, "with-third")
```