---
title: 'Fun with Random Numbers: Heavy Keeper'
date: '2023-08-21'
draft: true
#slug: fun-with-random-numbers-heavy-keeper
---

You can count the most frequent items in a stream efficiently in time and space.

https://www.usenix.org/system/files/conference/atc18/atc18-gong.pdf

```{r}
library(tidyverse)
```

```{r}
register <- function() {
  # A Heavy Keeper Register keeps a value from the stream and a counter
  value <- "☃"
  counter <- 0

  function(val = NA) {
    if (is.na(val)) {
      # If we don't pass a value, read the current info from the register.
      return(tibble(RegisterValue = value, Counter = counter))
    }

    if (counter == 0) {
      # If the counter is currently zero, set the value to the passed in
      # value and increment the counter.
      value <<- val
      counter <<- 1
    } else if (val == value) {
      # (N.B. counter != 0)
      # If the val passed in is the value in the register, increment
      # the counter.
      counter <<- counter + 1
    } else if (runif(1) < 1.08^-counter) {
      # (N.B. counter != 0)
      # (N.B. val != value)
      # Pick a number between 0 and 1.
      # If the number is less than 1 / 1.08^counter...decrement the count.
      counter <<- counter - 1
    }
    return(tibble(RegisterValue = value, Counter = counter))
  }
}

# Trial
# New Registers
# New Stream

nr <- 30

get_sample <- \() tibble(Id = 1:1000,
                         Value = sample(1:100,
                                        1000,
                                        replace = TRUE,
                                        prob = exp(1:100))) %>%
                  mutate(RegisterId = (digest::digest2int(as.character(Value)) %% nr) + 1)

get_registers <- \() tibble(RegisterId = 1:nr) %>%
  mutate(Register = map(RegisterId, \(x) register()))

count_sample <- \(sample, registers) sample %>%
  inner_join(registers) %>%
  mutate(output = map2(Value, Register, \(x,y) y(x))) %>%
  unnest(output) %>%
  inner_join(sample %>% count(Value, name = "TrueCount"), by = c("RegisterValue" = "Value"))

le_results <- tibble(Trial = 1:2) %>%
  mutate(Sample = map(Trial, \(x) get_sample())) %>%
  mutate(Registers = map(Trial, \(x) get_registers())) %>%
  mutate(Results = map2(Sample, Registers, count_sample)) %>%
  unnest(Results)
```

```{r}
le_results %>%
  select(Trial, Id, Value, RegisterId, RegisterValue, Counter) %>%
  filter(Trial == 2) %>%
  ggplot(aes(Id, Counter)) +
  geom_line() + 
  facet_wrap(~ RegisterId) 
```

```{r}
le_results %>%
  arrange(desc(Trial), desc(Id)) %>%
  distinct(Trial, RegisterId, .keep_all = TRUE) %>%
  select(Trial, RegisterId, RegisterValue, Counter, TrueCount) %>%
  mutate(ErrorPercentage = (Counter - TrueCount) / TrueCount) %>%
  ggplot(aes(ErrorPercentage)) +
  geom_density() 
```

